### ISSUE TITLE
Fails to build on 32 bit arch (i386)

### ISSUE THREAD

**Issue by nunotexbsd** [pjbgf/sha1cd#6]
FreeBSD 12.3 i386 / go 1.19.3

Building https://github.com/go-git/go-git:
`pjbgf:sha1cd:v0.2.0:pjbgf_sha1cd/vendor/github.com/pjbgf/sha1cd`

```
# github.com/pjbgf/sha1cd/cgo
vendor/github.com/pjbgf/sha1cd/cgo/sha1_nix.go:19:31: cannot use (_Ctype_ulong)(len(p)) (value of type _Ctype_ulong) as type _Ctype_uint in variable declaration
```

Are i386 or other 32 bit archs supported?

Thanks

**Comment by martinlindhe** [comment]
I see the same error but on gcc x86_64-pc-msys 11.3

**Comment by yann-soubeyrand** [comment]
Hello @nunotexbsd,
Can you try my PR to see if it fixes your issue?
You can use the following directive in your go.mod file:
`replace github.com/pjbgf/sha1cd v0.2.2 => github.com/yann-soubeyrand/sha1cd fix-type-cast`.

**Comment by pjbgf** [comment]
`github.com/pjbgf/sha1cd v0.2.3` has now being released with the fix.
