### ISSUE TITLE
Fails to build on x86_64-pc-msys

### ISSUE THREAD

**Issue by martinlindhe** [pjbgf/sha1cd#8]
I see a similar error to #6, but different arch and different types so i opened a separate issue.

on gcc x86_64-pc-msys 11.3

```
# github.com/pjbgf/sha1cd/cgo
..\..\..\go\pkg\mod\github.com\pjbgf\sha1cd@v0.2.2\cgo\sha1_windows.go:19:31: cannot use (_Ctype_ulonglong)(len(p)) (value of type _Ctype_ulonglong) as type _Ctype_ulong in variable declaration
```

**Comment by yann-soubeyrand** [comment]
Hello @martinlindhe,
Can you try my PR to see if it fixes your issue?
You can use the following directive in your go.mod file:
`replace github.com/pjbgf/sha1cd v0.2.2 => github.com/yann-soubeyrand/sha1cd fix-type-cast`.

**Comment by martinlindhe** [comment]
Confirmed working with the fix-type-cast branch!

**Comment by pjbgf** [comment]
`github.com/pjbgf/sha1cd v0.2.3` has now being released with the fix.

**Comment by martinlindhe** [comment]
@pjbgf Thank you so much!
