### ISSUE TITLE
Clarify copyright and licenses of files in test/testdata/files

### ISSUE THREAD

**Issue by Maytha8** [pjbgf/sha1cd#87]
No copyright or license information has been provided for these files, and it is clear they've been sourced from elsewhere.

sha-mbles-1.bin and sha-mbles-2.bin seem to be from [SHA-mbles.github.io](https://github.com/SHA-mbles/SHA-mbles.github.io) and appear to be licensed under the [MIT license](https://github.com/SHA-mbles/SHA-mbles.github.io/blob/master/LICENSE).

shattered-1.pdf and shattered-2.pdf seem to be from [shattered.io](https://shattered.io), but I was not able to find any licensing information.

**Comment by pjbgf** [comment]
The copyright information for all external files can be found at https://github.com/pjbgf/sha1cd/tree/main/cgo. Those files were all sourced from https://github.com/cr-marcstevens/sha1collisiondetection and are under [MIT license](https://github.com/cr-marcstevens/sha1collisiondetection/blob/master/LICENSE.txt).

**Comment by pjbgf** [comment]
Closing as per above. Happy to reopen in case more information is needed.
